language: python
python:
  - "3.6"
cache: pip
install:
  - pip install ../Pyhparser/
  - pip install coverage
script:
  # - python -m unittest
  - coverage run tests/tests.py
notifications:
  email: false